services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=swipe_sports
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=8080
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - swipe-sports-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=swipe_sports
      - MYSQL_USER=swipe_user
      - MYSQL_PASSWORD=swipe_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
    networks:
      - swipe-sports-network

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - swipe-sports-network

volumes:
  mysql_data:

networks:
  swipe-sports-network:
    driver: bridge
